import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import './globals.css';
import Header from './layouts/Header';
import Navbar from './layouts/Navbar';

export const metadata: Metadata = {
    title: 'OAuth Admin',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <AppRouterCacheProvider>
                    <Header>
                        <Navbar>{children}</Navbar>
                    </Header>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
